In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./data/기상청ASOS관측.csv',index_col=0)
df.head(3)

,지점 번호,관측지점,시간,평균 기온,최저 기온,최저 기온 시각,최고 기온,최대 기온 시각,10분 최다 강수량,10분 최다강수량 시각,...,0.5m 지중온도,1.0m 지중온도,1.5m 지중온도,3.0m 지중온도,5.0m 지중온도,합계 대형증발량,합계 소형증발량,9-9강수,일기현상,안개 계속 시간
0,105,강릉,1980-01-01,3.0,-0.4,714,7.0,1549.0,NaN,NaN,...,6.1,9.1,11.4,15.0,15.4,NaN,0.9,2.6,{비}2218-{비}{강도0}2400-,NaN
1,105,강릉,1980-01-02,6.0,3.5,207,8.4,1500.0,NaN,NaN,...,6.7,9.0,11.1,14.8,15.5,NaN,1.5,1.4,-{비}-{비}{강도0}0300-{비}{강도0}0600-{비}{강도0}0900-{비...,NaN
2,105,강릉,1980-01-03,7.5,4.1,1810,12.8,1330.0,NaN,NaN,...,6.8,9.0,11.0,14.8,15.3,NaN,2.2,NaN,NaN,NaN

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 176586 entries, 0 to 365
Data columns (total 62 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   지점 번호          176586 non-null  int64
 1   관측지점           176586 non-null  object
 2   시간             176586 non-null  object
 3   평균 기온          176581 non-null  float64
 4   최저 기온          176584 non-null  float64
 5   최저 기온 시각       176586 non-null  int64
 6   최고 기온          176583 non-null  float64
 7   최대 기온 시각       176584 non-null  float64
 8   10분 최다 강수량     44432 non-null   float64
 9   10분 최다강수량 시각   33429 non-null   float64
 10  1시간 최다강수량      44421 non-null   float64
 11  1시간 최다 강수량 시각  33543 non-null   float64
 12  sumRnDur       67858 non-null   float64
 13  일강수량           70401 non-null   float64
 14  최대 순간풍속        176561 non-null  float64
 15  최대 순간 풍속 풍향    176559 non-null  float64
 16  최대 순간풍속 시간     176561 non-null  float64
 17  최대 풍속          176571 non-null  float64
 18  최대 풍속 풍향       176571 non-null  float64
 19  최대 풍속 시각       176573 non-null  float64
 20  평균 풍속          176555 non-null  float64
 21  풍정합            176552 non-null  float64
 22  최대 풍향          176371 non-null  float64
 23  평균 이슬점온도       176581 non-null  float64
 24  최소 상대습도        176581 non-null  float64
 25  평균 상대습도 시각     176582 non-null  float64
 26  평균 상대습도        176577 non-null  float64
 27  평균 증기압         176576 non-null  float64
 28  평균 현지기압        176572 non-null  float64
 29  최고 해면 기압       176571 non-null  float64
 30  최고 해면기압 시각     176578 non-null  float64
 31  최저 해면기압        176567 non-null  float64
 32  최저 해면기압 시각     176577 non-null  float64
 33  평균 해면기압        176573 non-null  float64
 34  가조시간           176581 non-null  float64
 35  합계 일조 시간       176490 non-null  float64
 36  1시간 최다 일사량 시각  147010 non-null  float64
 37  1시간 최다 일사량     147012 non-null  float64
 38  합계 일사          152696 non-null  float64
 39  일 최심신적설        6938 non-null    float64
 40  일 최심신적설 시각     6586 non-null    float64
 41  일 최심적설         10878 non-null   float64
 42  일 최심적설 시각      10725 non-null   float64
 43  합계 3시간 신적설     6914 non-null    float64
 44  평균 전운량         170388 non-null  float64
 45  평균 중하층운량       169981 non-null  float64
 46  평균 지면온도        176567 non-null  float64
 47  최저 초상온도        176569 non-null  float64
 48  평균 5cm 지중온도    133896 non-null  float64
 49  평균10cm 지중온도    133852 non-null  float64
 50  평균 20cm 지중온도   133910 non-null  float64
 51  평균 30cm 지중온도   133899 non-null  float64
 52  0.5m 지중온도      133906 non-null  float64
 53  1.0m 지중온도      133910 non-null  float64
 54  1.5m 지중온도      109605 non-null  float64
 55  3.0m 지중온도      109603 non-null  float64
 56  5.0m 지중온도      109596 non-null  float64
 57  합계 대형증발량       96662 non-null   float64
 58  합계 소형증발량       142474 non-null  float64
 59  9-9강수          61584 non-null   float64
 60  일기현상           114903 non-null  object
 61  안개 계속 시간       11290 non-null   float64
dtypes: float64(57), int64(2), object(3)
memory usage: 84.9+ MB

In [ ]:
# 공통

# '평균 기온'
# '일강수량'
# '최대 순간풍속', '최대 순간 풍속 풍향', '최대 풍속','최대 풍속 풍향'
# '평균 풍속'
# '풍정합'

# 평균 이슬점온도'

# '평균 상대습도'

# '평균 현지기압','평균 해면기압'

#  '가조시간', '합계 일조 시간', '1시간 최다 일사량 시각','1시간 최다 일사량', '합계 일사'

#  '일 최심신적설', ''일 최심적설',

#  '평균 전운량','평균 중하층운량', 

# '평균 지면온도', '평균 5cm 지중온도','평균10cm 지중온도', 

# '합계 대형증발량', '합계 소형증발량',

In [ ]:
df_feature =

In [ ]:
# 서울,경기도 : 서울
# 강원도 : 강릉, 춘천
# 충청남도 : 대전
# 충청북도 : 청주
# 전라북도 : 전주
# 전라남도 : 광주
# 경상북도 : 대구
# 경상남도 : 부산
# 제주도 : 제주

In [7]:
df['관측지점'].unique()

array(['강릉', '춘천', '울릉도', '광주', '대구', '대전', '부산', '서울', '전주', '제주', '청주',
       '백령도'], dtype=object)

In [32]:
# 서울,경기도

df[(df['관측지점']== '서울')]

,지점 번호,관측지점,시간,평균 기온,최저 기온,최저 기온 시각,최고 기온,최대 기온 시각,10분 최다 강수량,10분 최다강수량 시각,...,0.5m 지중온도,1.0m 지중온도,1.5m 지중온도,3.0m 지중온도,5.0m 지중온도,합계 대형증발량,합계 소형증발량,9-9강수,일기현상,안개 계속 시간
0,108,서울,1980-01-01,3.8,0.5,0,6.6,1600.0,NaN,NaN,...,2.6,6.3,9.3,14.8,15.9,NaN,1.8,4.1,-{박무}-0210. {달무리}0430-0515. {비}2220-{비}{강도0}2...,NaN
1,108,서울,1980-01-02,4.7,3.5,440,5.9,1958.0,NaN,NaN,...,2.6,6.1,9.1,14.6,15.8,NaN,0.8,5.8,-{비}-{비}{강도0}0300-{비}{강도0}0600-{비}{강도0}0900-{비...,NaN
2,108,서울,1980-01-03,3.8,-0.5,2400,6.2,1530.0,NaN,NaN,...,2.8,6.1,9.1,14.5,15.7,NaN,0.9,NaN,-{박무}-{박무}{강도1}0300-{박무}{강도0}0600-{박무}{강도1}090...,NaN
3,108,서울,1980-01-04,-3.2,-6.9,2400,-0.5,0.0,NaN,NaN,...,2.8,5.9,8.9,14.5,15.7,NaN,1.5,NaN,-{박무}-0230. {달무리}0215-0620.,NaN
4,108,서울,1980-01-05,-5.3,-9.1,803,-1.0,1554.0,NaN,NaN,...,2.8,5.9,8.8,14.5,15.7,NaN,2.1,1.9,{눈}2048-{눈}{강도0}2100-{눈}{강도0}2400-,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,108,서울,2021-12-28,-4.1,-8.5,712,-0.9,1600.0,NaN,NaN,...,3.3,7.4,10.8,15.4,17.4,0.6,0.9,0.2,NaN,NaN
362,108,서울,2021-12-29,0.4,-3.8,154,5.9,1518.0,NaN,NaN,...,3.2,7.1,10.7,15.3,17.3,1.0,1.4,0.0,{눈}0255-{눈}{강도0}0300-0310. {싸락눈}0355-0505. {박무...,NaN
363,108,서울,2021-12-30,-3.9,-6.8,714,0.2,1531.0,NaN,NaN,...,3.0,6.9,10.5,15.2,17.3,1.5,2.1,0.0,{눈}1745-{눈}{강도0}1800-1815.,NaN
364,108,서울,2021-12-31,-6.7,-8.8,745,-3.9,1510.0,NaN,NaN,...,2.9,6.7,10.3,15.2,17.3,1.3,1.9,NaN,NaN,NaN
365,108,서울,2022-01-01,-4.3,-10.2,710,2.3,1544.0,NaN,NaN,...,2.7,6.6,10.1,15.1,17.2,1.3,1.8,0.3,NaN,NaN

In [29]:
# 강원도
df[(df['관측지점']== '춘천') | (df['관측지점']== '강릉')]

,지점 번호,관측지점,시간,평균 기온,최저 기온,최저 기온 시각,최고 기온,최대 기온 시각,10분 최다 강수량,10분 최다강수량 시각,...,0.5m 지중온도,1.0m 지중온도,1.5m 지중온도,3.0m 지중온도,5.0m 지중온도,합계 대형증발량,합계 소형증발량,9-9강수,일기현상,안개 계속 시간
0,105,강릉,1980-01-01,3.0,-0.4,714,7.0,1549.0,NaN,NaN,...,6.1,9.1,11.4,15.0,15.4,NaN,0.9,2.6,{비}2218-{비}{강도0}2400-,NaN
1,105,강릉,1980-01-02,6.0,3.5,207,8.4,1500.0,NaN,NaN,...,6.7,9.0,11.1,14.8,15.5,NaN,1.5,1.4,-{비}-{비}{강도0}0300-{비}{강도0}0600-{비}{강도0}0900-{비...,NaN
2,105,강릉,1980-01-03,7.5,4.1,1810,12.8,1330.0,NaN,NaN,...,6.8,9.0,11.0,14.8,15.3,NaN,2.2,NaN,NaN,NaN
3,105,강릉,1980-01-04,4.1,-0.8,2356,6.8,1206.0,NaN,NaN,...,7.0,9.1,11.0,14.7,15.5,NaN,1.8,1.5,{비}1406-{싸락눈}1437-{진눈깨비}1450-{진눈깨비}{강도0}1500-{...,NaN
4,105,강릉,1980-01-05,-0.8,-3.9,746,4.3,1224.0,NaN,NaN,...,7.3,9.1,10.8,14.7,15.4,NaN,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,101,춘천,2021-12-28,-5.4,-11.9,238,-1.4,1619.0,NaN,NaN,...,2.0,7.2,10.5,15.2,16.7,0.4,0.6,0.5,NaN,NaN
362,101,춘천,2021-12-29,-0.8,-6.5,311,3.9,1546.0,NaN,NaN,...,2.0,7.1,10.4,15.2,16.8,0.9,1.2,0.1,NaN,NaN
363,101,춘천,2021-12-30,-3.1,-6.2,2351,0.6,1455.0,NaN,NaN,...,1.9,6.9,10.3,15.1,16.7,1.5,2.2,NaN,NaN,NaN
364,101,춘천,2021-12-31,-7.0,-11.8,2357,-1.9,1455.0,NaN,NaN,...,1.6,6.7,10.1,14.9,16.6,1.1,1.6,NaN,NaN,NaN
365,101,춘천,2022-01-01,-8.2,-14.9,614,0.0,1535.0,NaN,NaN,...,1.3,6.5,9.9,14.8,16.5,0.8,1.2,0.0,NaN,NaN

In [33]:
# 충청남도 : 대전

df[(df['관측지점']== '대전')]

,지점 번호,관측지점,시간,평균 기온,최저 기온,최저 기온 시각,최고 기온,최대 기온 시각,10분 최다 강수량,10분 최다강수량 시각,...,0.5m 지중온도,1.0m 지중온도,1.5m 지중온도,3.0m 지중온도,5.0m 지중온도,합계 대형증발량,합계 소형증발량,9-9강수,일기현상,안개 계속 시간
0,133,대전,1980-01-01,3.7,-2.3,123,6.3,2344.0,NaN,NaN,...,4.6,7.7,10.9,14.7,16.3,NaN,1.1,2.9,{비}1450-{비}{강도0}1500-1506. {비}2350-{비}{강도0}24...,NaN
1,133,대전,1980-01-02,6.3,5.1,500,8.3,1405.0,NaN,NaN,...,4.9,7.7,10.7,14.6,16.3,NaN,0.5,3.4,-{비}-{비}{강도0}0300-0545. {비}0705-{비}{강도0}0900-...,NaN
2,133,대전,1980-01-03,4.7,2.3,2400,5.9,6.0,NaN,NaN,...,5.7,7.7,10.6,14.5,16.3,NaN,0.4,0.4,-{박무}-{박무}{강도0}0300-{박무}{강도0}0600-{박무}{강도0}090...,NaN
3,133,대전,1980-01-04,0.3,-3.8,2357,3.1,1444.0,NaN,NaN,...,5.7,7.7,10.4,14.4,16.2,NaN,1.6,NaN,NaN,NaN
4,133,대전,1980-01-05,-5.1,-8.5,830,-0.1,1553.0,NaN,NaN,...,5.4,7.8,10.3,14.3,16.2,NaN,1.4,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,133,대전,2021-12-28,-0.5,-3.2,622,3.5,1539.0,NaN,NaN,...,3.3,7.4,10.1,15.6,18.2,0.5,0.7,0.0,-{박무}-{박무}{강도0}0300-{박무}{강도1}0600-{박무}{강도1}090...,NaN
362,133,대전,2021-12-29,2.4,-2.1,47,7.2,1305.0,NaN,NaN,...,3.1,7.1,10.0,15.6,18.2,1.0,1.5,0.0,-{박무}-{박무}{강도1}0300-{박무}{강도1}0600-{박무}{강도0}090...,NaN
363,133,대전,2021-12-30,-1.4,-4.5,2359,3.0,1323.0,NaN,NaN,...,3.1,6.9,9.8,15.5,18.2,0.9,1.4,0.5,{눈}0150-{눈}{강도0}0300-0355. {눈}1425-{눈}{강도0}150...,NaN
364,133,대전,2021-12-31,-5.0,-8.3,605,0.5,1434.0,NaN,NaN,...,3.0,6.8,9.6,15.5,18.2,1.3,1.9,NaN,-{눈}-0040.,NaN
365,133,대전,2022-01-01,-4.4,-10.0,637,2.3,1516.0,NaN,NaN,...,3.0,6.6,9.4,15.3,18.1,1.1,1.6,0.0,NaN,NaN